I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2056, in script
    show doctor happy at sycamore_small, right
  File "game/script.rpy", line 2056, in <module>
    show doctor happy at sycamore_small, right
NameError: name 'dissolv' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2056, in script
    show doctor happy at sycamore_small, right
  File "C:\Users\Lowie Suarez\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 1370, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\Lowie Suarez\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Lowie Suarez\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 2056, in <module>
    show doctor happy at sycamore_small, right
NameError: name 'dissolv' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
 
Sat Apr  5 01:28:00 2025
