I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 185, in script
    scene clinic at clinic
  File "game/script.rpy", line 185, in <module>
    scene clinic at clinic
NameError: name 'clinic' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 185, in script
    scene clinic at clinic
  File "C:\Users\Lowie Suarez\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 1258, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Lowie Suarez\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 1083, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\Lowie Suarez\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 1083, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\Lowie Suarez\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Lowie Suarez\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 185, in <module>
    scene clinic at clinic
NameError: name 'clinic' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
DoctorsOrder 1.0
Mon Mar 24 18:39:55 2025
